"""initial_schema

Revision ID: 3578c1d8b2b3
Revises: 
Create Date: 2026-06-28 02:38:50.322530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3578c1d8b2b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('direct', 'group')", name='ck_conversation_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversations_updated', ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_phone', ['phone_number'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('contact_user_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_user_id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_owner', ['owner_id'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index('idx_cp_conversation', ['conversation_id'], unique=False)
        batch_op.create_index('idx_cp_user', ['user_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('reply_to_id', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('disappears_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'image', 'file', 'system')", name='ck_message_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_disappears', ['disappears_at'], unique=False, sqlite_where=sa.text('disappears_at IS NOT NULL'))
        batch_op.create_index('idx_messages_reply', ['reply_to_id'], unique=False, sqlite_where=sa.text('reply_to_id IS NOT NULL'))
        batch_op.create_index('idx_messages_sender', ['sender_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_sessions_token', ['token'], unique=False)
        batch_op.create_index('idx_sessions_user', ['user_id'], unique=False)

    op.create_table('message_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('delivered', 'read')", name='ck_message_status'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id')
    )
    with op.batch_alter_table('message_status', schema=None) as batch_op:
        batch_op.create_index('idx_ms_message', ['message_id'], unique=False)
        batch_op.create_index('idx_ms_user', ['user_id'], unique=False)

    op.create_table('reactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index('idx_reactions_message', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_reactions_message')

    op.drop_table('reactions')
    with op.batch_alter_table('message_status', schema=None) as batch_op:
        batch_op.drop_index('idx_ms_user')
        batch_op.drop_index('idx_ms_message')

    op.drop_table('message_status')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_user')
        batch_op.drop_index('idx_sessions_token')
        batch_op.drop_index('idx_sessions_expires_at')

    op.drop_table('sessions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_sender')
        batch_op.drop_index('idx_messages_reply', sqlite_where=sa.text('reply_to_id IS NOT NULL'))
        batch_op.drop_index('idx_messages_disappears', sqlite_where=sa.text('disappears_at IS NOT NULL'))
        batch_op.drop_index('idx_messages_conversation')

    op.drop_table('messages')
    op.drop_table('groups')
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_cp_user')
        batch_op.drop_index('idx_cp_conversation')

    op.drop_table('conversation_participants')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('idx_contacts_owner')

    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_phone')

    op.drop_table('users')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversations_updated')

    op.drop_table('conversations')
    # ### end Alembic commands ###
