name: Keep Render alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date
          curl -v https://signal-clone-2han.onrender.com/health